### Get task by ID
GET http://localhost:8080/task/1
Accept: application/json

### Create task with ID '1'
POST http://localhost:8080/task/1
Content-Type: application/json

{
  "id": "1",
  "name": "sample-task",
  "description": "just do it",
  "duration": "2h"
}

### ingress POST
POST localhost/task/1
Content-Type: application/json

{
"id": "1",
"name": "sample-task",
"description": "just do it",
"duration": "2h"
}

### ingress GET
GET localhost/task/1
Accept: application/json

### Get task by ID
GET http://localhost:8080/task/1
Accept: application/json

### Create task with ID '2'
POST http://localhost:8080/task/2
Content-Type: application/json

{
  "id": "2",
  "name": "other-task",
  "description": "you better do it",
  "duration": "5h"
}

### Get task complexity
POST http://localhost:3000/complexity
Content-Type: application/json

{
  "duration": "2h30m"
}